trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
        - task: MavenAuthenticate@0
          inputs:
            artifactsFeeds: 'java-app' # Replace with your Azure Artifacts feed name

        - script: mvn clean package
          displayName: 'Build Java Project'

        - script: |
            mvn deploy -DaltDeploymentRepository=gitlab-repo::default::https://gitlab-ci-token:$(MAVEN_SETTINGS_FILE)@gitlab.com/api/v4/projects/1/packages/maven
          displayName: 'Deploy to Azure Artifacts'
          env:
            MAVEN_SETTINGS_FILE: $(MAVEN_SETTINGS_PATH) # Optional, if using a custom settings.xml
# trigger:
# - master

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - task: MavenAuthenticate@1
#   inputs:
#     artifactsFeeds: 'java-app' # Replace with your Azure Artifacts feed name

# - script: mvn clean package
#   displayName: 'Build Java Project'

# - script: mvn deploy
#   displayName: 'Deploy to Azure Artifacts'
#   env:
#     MAVEN_SETTINGS_FILE: $(MAVEN_SETTINGS_PATH) # Optional, if using a custom settings.xml
