trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'

          # Publish the JAR file as an artifact
          - publish: $(System.DefaultWorkingDirectory)/target
            artifact: drop
