# azure-pipelines.yml
trigger:
  branches:
    include:
      - master  # or 'master' or any other branch you want to trigger the build

pool:
  vmImage: 'ubuntu-latest'  # Using the latest Ubuntu image for the build agent

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Adjust if your pom.xml is in a subdirectory
    goals: 'clean package'
    options: ''
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'  # You can set the JDK version (1.8, 11, etc.)
    mavenVersionOption: 'Default'
    mavenSetM2Home: true
